config/routes.rb
Crmsys::Application.routes.draw do

  root :to => 'contacts#index'

  resources :accounts
  resources :attachmends
  resources :comments
  resources :contacts do
    member do
      get  :quick_info
      post :update_avatar
    end
    collection do
      get  :imexport
      get  :export
      post :import
      post :mass_destroy
    end
  end
  resources :people
  resources :companies
  resources :ware_items
  resources :sale_items

  resources :ware_houses do
    member do
      get :edit_ware_items
      put :update_ware_items
    end
  end

  resources :sales do
    member do
      get  :cancel
      post :sip
      get  :quick_info
    end
    collection do 
      post :mass_destroy
      post :mass_state
    end
  end

  resources :cases do
    member do 
      get  :cancel
      get  :report
      get  :print
      post :sip
      get  :quick_info
      post :update_inventory
    end
    collection do
      post :mass_destroy
      post :mass_state
    end
  end

  resources :tasks do
    member do
      put :accept
      put :move
      get :quick_info
    end
    collection do
      post :mass_destroy
      post :mass_accept
      get  :mass_new
    end
  end

  namespace :settings do
    resources :account
    resources :color_schemes
    resources :sale_states do
      post :mass_destroy, :on => :collection
    end
    resources :case_states do
      post :mass_destroy, :on => :collection
    end
    resources :users do
      post :mass_destroy, :on => :collection
    end
    resources :user_groups do
      post :mass_destroy, :on => :collection
    end
    resources :recent_records do
      post :mass_destroy, :on => :collection
    end
    namespace :tariff_plans do
      resources :account_tariff_plans do
	post :mass_destroy, :on => :collection
      end
    end
  end

  namespace :reports do
    #root :to => 'sales'
    resources :tasks do
      collection do
        get  :punctuality
	post :punctuality
        get  :outcoming
	post :outcoming
      end
    end
    resources :users do
      collection do
	get  :activity
	post :activity
      end
    end
    resources :contacts do
      collection do
	get  :problem_clients
	post :problem_clients
      end
    end
    resources :logs do
      collection do
	get  :logs_view
	post :logs_view
      end
    end
  end

  match 'fuzzy/search' => 'fuzzy#search', :as => :fuzzy_search
  match 'users/:id/update_avatar' => 'users#update_avatar', :as => :update_avatar_user
  match 'feedback/create' => 'feedback#create'

  match 'sign_out' => 'clearance/sessions#destroy', :as => :sign_out
  
end

app/models/account.rb
class Account < ActiveRecord::Base
  include Settings
  is_paranoid

  has_many :users,          :dependent => :destroy
  has_many :admins,         :dependent => :destroy, :class_name => 'User', :conditions => {:is_admin => true}
  has_many :commodities,    :dependent => :destroy
  has_many :ware_houses,    :dependent => :destroy
  has_many :tasks,          :dependent => :destroy
  has_many :comments,       :dependent => :destroy
  has_many :projects,       :dependent => :destroy
  has_many :discounts,      :dependent => :destroy
  has_many :measures,       :dependent => :destroy
  has_many :categories,     :dependent => :destroy
  has_many :sales,          :dependent => :destroy
  has_many :services,       :dependent => :destroy, :class_name => 'Service'
  has_many :wares,          :dependent => :destroy, :class_name => 'Ware'
  has_many :user_groups,    :dependent => :destroy
  has_many :attachmends,    :dependent => :destroy
  # контакты -------------------------------------------------------------------
  has_many :contacts,       :dependent => :destroy
  has_many :people,         :dependent => :destroy
  has_many :companies,      :dependent => :destroy
  has_many :banks,          :dependent => :destroy
  # типы -----------------------------------------------------------------------
  has_many :types,          :dependent => :destroy
  has_many :address_types,  :dependent => :destroy
  has_many :email_types,    :dependent => :destroy
  has_many :im_protocols,   :dependent => :destroy
  has_many :im_types,       :dependent => :destroy
  has_many :phone_types,    :dependent => :destroy
  has_many :url_types,      :dependent => :destroy

  belongs_to :tariff_plan, :class_name => 'AccountTariffPlan'

  accepts_nested_attributes_for :admins

  validate :end_time, :presense => true
  validate :name, :presense => true

  def convert
    [name.to_s, id]
  end

  #-----------------------------------------------------------------------------
  def statistic
    active_records = 0
    deteled_records = 0
    Account.reflections.
      select{|r| r[1].macro == :has_many or r[1].macro == :has_one}.
      map{|r| r[0]}.
      select{|r|
        begin
          o = Object.const_get(r.to_s.singularize.camelize)
          o.is_a?(Class) and o.superclass == ActiveRecord::Base
        rescue
          false
        end
      }.
      each do |r|
        active_records += send(r).count
        deteled_records += send(r).count_destroyed_only(:conditions => {:account_id => id})
      end
    return {
      :active_records => active_records,
      :deleted_records => deteled_records}
  end

  #-----------------------------------------------------------------------------
  def can_be_edited user=$current_user
    user.is_admin? and user.account.is_director? and not self.is_director?
  end
  def can_be_deleted user=$current_user
    user.is_admin? and user.account.is_director? and not self.is_director?
  end

  def self.director
    find(:first, :conditions => {:is_director => true})
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  before_filter :accounts_admin_only, :except => [:index, :show]
  before_filter :find_account, :only => [:show, :edit, :update, :destroy]

  #-----------------------------------------------------------------------------
  def index
    before_render
  end

  #-----------------------------------------------------------------------------
  def new
    @account = Account.new(:end_time => Time.now + 1.month)
    @account.admins[0] = User.new
  end

  #-----------------------------------------------------------------------------
  def create
    settings = params[:account][:settings]
    params[:account].delete(:settings)
    @account = Account.new(params[:account])
    @account.admins[0].email_confirmed = true
    @account.admins[0].is_admin = true
    responds_to_parent do
      if @account.save
        # копируем записи директора во вновь созданный аккаунт
        # установка локали нужна для локализации при копировании
        save_locale = I18n.locale
        I18n.locale = settings[:locale]
        clone_items(:types)
        clone_items(:measures)
        I18n.locale = save_locale
        # настройки по умолчанию
        @account.settings.locale = settings[:locale]
        @account.settings.save
        @account.admins[0].settings.locale = settings[:locale]
        @account.admins[0].settings.save
        # рендер
        before_render
        render :action => :create
      else
        render :action => :new
      end
    end
  end

  #-----------------------------------------------------------------------------
  def update
    settings = params[:account][:settings]
    params[:account].delete(:settings)
    responds_to_parent do
      if @account.update_attributes(params[:account])
        @account.settings.locale = settings[:locale]
        @account.settings.save
        before_render
        render :action => :update
      else
        render :action => :edit
      end
    end
  end

  #-----------------------------------------------------------------------------
  def destroy
    @account.destroy
    before_render
  end


private

  #-----------------------------------------------------------------------------
  def find_account
    @account = Account.find(params[:id])
    @statistic = params[:statistic] ? @account.statistic : nil
  end

  #-----------------------------------------------------------------------------
  def before_render
    @accounts = Account.find(:all)
  end

  #-----------------------------------------------------------------------------
  def clone_items items
    clone_items = []
    current_user.account.send(items).each do |item|
      clone = item.clone
      clone.user_id = @account.admins[0].id
      clone.created_at = nil
      clone.updated_at = nil
      # теперь проходим по всем строковым полям клона и, если значение поля
      # начинается с 't(:', то выполняем локализацию
      clone.attributes.each_key do |k|
        v = clone.attributes[k]
        if v.is_a?(String) and v.match(/^t\(:([a-z_]+)\)$/i)
          begin
            clone.send(:"#{k}=", I18n::t($1))
          rescue
          end
        end
      end
      clone_items << clone
    end
    @account.send(:"#{items}=", clone_items)
  end

end

app/controllers/settings/account_controller.rb
class Settings::AccountController < ApplicationController

  before_filter :admin_only

  #-----------------------------------------------------------------------------
  def index
    before_render
  end

  #-----------------------------------------------------------------------------
  def update
    @account = Account.find(params[:id])
    if current_user.account == @account
      @account.name = params[:account][:name]
      @account.save
      @account.settings.locale = params[:account][:settings][:locale]
      @account.settings.save
    else
      @account = current_user.account
    end
    responds_to_parent do
      render :action => :update
    end
  end


private

  #-----------------------------------------------------------------------------
  def before_render
    @account = current_user.account
  end

end

app/views/shared/accounts/_account.html.erb
<tr class="item_line" id="<%= "account_line_#{account.id}" %>">
  <td class="item_opers">
    <% if account.can_be_edited %>
    <a class="item_chg_link"
      href="#"
      title="<%= t(:edit) %>"
      onclick="<%= remote_function :url => edit_account_path(account), :method => :get %>">
    </a>
    <% end %>
    <% if account.can_be_deleted %>
    <a class="item_del_link"
      href="#"
      title="<%= t(:delete) %>"
      onclick="<%= remote_function :url => account_path(account), :method => :delete, :confirm => t(:confirm_delete) %>">
    </a>
    <% end %>
  </td>
  <td class="info">
    <%= link_to h(account.name), :url => account_path(account), :method => :get, :html => {:class => :link_class}, :remote => true %><br />
    <b><%= t(:created) %>: </b><%= I18n.l(account.created_at, :format => "%a, %d %b %Y") %>
    <b><%= t(:expiry) %>: </b><%= I18n.l(account.end_time, :format => "%a, %d %b %Y") %>
    <b><%= t(:users) %>: </b><%= account.users.size %>
  </td>
</tr>

app/views/shared/accounts/_accounts_list.html.erb
<table class='accounts_table'>
  <%= render :partial => 'shared/accounts/account', :collection => accounts %>
</table>

app/views/shared/accounts/_admin.html.erb
<b><%= admin.name %></b>&nbsp;(<%= admin.email %>)<br />

app/views/shared/accounts/_form.html.erb
<% url, method = get_url_and_method(account) %>
<div class="sheet_title"><%= account.new_record? ? t(:new_account) : account.name %></div>
<% semantic_form_for account, :url => url, :html => {:method => method, :target => 'target_frame'} do |form| %>
  <% form.inputs do %>
    <%= form.input :name, :label => t(:account_name) %>
    <%= form.input :end_time, :label => t(:expiry), :as => :date, :include_blank => false %>
    <%= form.input :tariff_plan, :label => t(:tariff_plan), :collection => AccountTariffPlan.all, :include_blank => false %>
  <% end %>
  <% form.inputs :for => :settings do |settings| %>
    <%= settings.input :locale, :label => t(:default_lang), :as => :radio, :collection => locales_collection, :selected => account.settings.locale %>
  <% end %>
  <% form.semantic_fields_for :admins, account.admins[0] do |admin_form| %>
    <b><%= t(:account_admin) %></b>
    <% admin_form.inputs do %>
      <%= admin_form.input :name, :label => t(:name) %>
      <%= admin_form.input :email, :label => t(:email) %>
      <%= admin_form.input :password, :label => t(account.new_record? ? :password : :password_if_need_change) %>
      <%= admin_form.input :password_confirmation, :label => t(:password_confirmation) %>
    <% end %>
  <% end %>
  <%= render :partial => 'shared/buttons', :locals => {:item => account, :buttons => [:submit,:cancel]} %>
<% end %>

app/views/shared/accounts/_show.html.erb
<%
  buttons = [:cancel] + (account.is_director? ? [] : [:edit, :delete])
%>
<div class="sheet_title"><%= account.name %></div>
<label><%= t(:created) %></label><%= I18n.l(account.created_at, :format => "%a, %d %b %Y") %><br />
<label><%= t(:expiry) %></label><%= I18n.l(account.end_time, :format => "%a, %d %b %Y") %><br />
<label><%= t(:default_lang) %></label><%= locale_name(account.settings.locale) %><br />
<label><%= t(:tariff_plan) %></label><%= account.tariff_plan.formatted_name{|x| loc_tdc(x)} %><br />
<% if statistic %>
  <label><%= t(:active_records) %></label><%= statistic[:active_records] %><br />
  <label><%= t(:deleted_records) %></label><%= statistic[:deleted_records] %><br />
<% else %>
  <%= link_to_remote t(:show_statistic), :url => account_path(account), :method => :get, :with => "'statistic=1'" %><br />
<% end %>
<%= render :partial => 'shared/hideble',
  :locals => {
    :title          => t(:admins),
    :size           => account.admins.size,
    :visible        => false,
    :title_class    => 'small bold',
    :content        => render(:partial => "shared/accounts/admin", :collection => account.admins)} %>
<% users = account.users - account.admins %>
<%= render :partial => 'shared/hideble',
  :locals => {
    :title          => t(:users),
    :size           => users.size,
    :visible        => false,
    :title_class    => 'small bold',
    :content        => render(:partial => "shared/accounts/user", :collection => users)} %>
<%= render :partial => 'shared/buttons', :locals => {:item => account, :buttons => buttons} %>

app/views/shared/accounts/_user.html.erb
<b><%= user.name %></b>&nbsp;(<%= user.email %>)<br />